; zero page addresses

LEVEL		= $8B
INL		= $8C
INH		= $8D
SCORE_LOW	= $8E
SCORE_HIGH	= $8F

TEMP1		= $90
BUTTON_COUNTDOWN= $94
MANS		= $96

SCORE_SPRITE_LOW_0      =       $A0
SCORE_SPRITE_LOW_1      =       $A1
SCORE_SPRITE_LOW_2      =       $A2
SCORE_SPRITE_LOW_3      =       $A3
SCORE_SPRITE_LOW_4      =       $A4
SCORE_SPRITE_LOW_5      =       $A5
SCORE_SPRITE_LOW_6      =       $A6

SCORE_SPRITE_HIGH_0     =       $A7
SCORE_SPRITE_HIGH_1     =       $A8
SCORE_SPRITE_HIGH_2     =       $A9
SCORE_SPRITE_HIGH_3     =       $AA
SCORE_SPRITE_HIGH_4     =       $AB
SCORE_SPRITE_HIGH_5     =       $AC
SCORE_SPRITE_HIGH_6     =       $AD

TEXT_COLOR              =       $AE
LEVEL_COLOR		=	$AF

MANS_SPRITE_0           =       $B0
MANS_SPRITE_1           =       $B1
MANS_SPRITE_2           =       $B2
MANS_SPRITE_3           =       $B3
MANS_SPRITE_4           =       $B4
MANS_SPRITE_5           =       $B5
MANS_SPRITE_6           =       $B6


LEVEL_SPRITE0           =       $C0
LEVEL_SPRITE1           =       $C1
LEVEL_SPRITE2           =       $C2
LEVEL_SPRITE3           =       $C3
LEVEL_SPRITE4           =       $C4
LEVEL_SPRITE5           =       $C5
LEVEL_SPRITE6           =       $C6
LEVEL_SPRITE7           =       $C7
LEVEL_SPRITE8           =       $C8
LEVEL_SPRITE9           =       $C9
LEVEL_SPRITE10          =       $CA
LEVEL_SPRITE11          =       $CB
LEVEL_SPRITE12          =       $CC
LEVEL_SPRITE13          =       $CD
LEVEL_SPRITE14          =       $CE
LEVEL_SPRITE15          =       $CF

