common_vblank = $FC00 + $00
common_overscan = $FC00 + $11
handle_music_chapter = $FC00 + $1B
cart_message = $FC00 + $200
cart_message0 = cart_message
cart_message1 = cart_message + $1E
cart_message2 = cart_message + $3C
cart_message3 = cart_message + $5A
cart_message4 = cart_message + $78
cart_message5 = cart_message + $96

text_sprite0 = $FC00 + $2B4
text_sprite1 = $FC00 + $2D8
text_sprite2 = $FC00 + $300
text_sprite3 = $FC00 + $324
text_sprite4 = $FC00 + $348
text_sprite5 = $FC00 + $36C

fine_adjust_table = $FC00 + $175
