	; note, upside down
	; hand sprite point
hand_sprite:
	.byte	$00,$00,$0E,$0E,$1F,$1F,$3F,$2F
	.byte	$6D,$4C,$08,$08,$08,$08,$08,$08

	; hand sprite grab
hand_sprite_grab:
	.byte	$00,$00,$3C,$3C,$7E,$7E,$7F,$FF
	.byte	$FF,$BF,$35,$55,$55,$54,$54,$10

hand_sprite_left:
	.byte	$00,$00,$1C,$0F,$1F,$0F,$1F,$0F
	.byte	$FF,$FF,$06,$0C,$18,$00,$00,$00

hand_sprite_right:
	.byte	$00,$00,$38,$F0,$F8,$F0,$F8,$F0
	.byte	$FF,$FF,$60,$30,$18,$00,$00,$00

hand_sprite_page:
	.byte	$00,$00,$FE,$FE,$FE,$FE,$FE,$FE
	.byte	$FE,$FE,$0E,$EE,$6E,$6E,$2E,$2E
