page_sprite:
	.byte $18
	.byte $0D
	.byte $0F
	.byte $7F
	.byte $5B
	.byte $1F
	.byte $1D
	.byte $1B
	.byte $00	;
	.byte $FF
	.byte $FF
	.byte $FF
	.byte $FF
	.byte $FF
	.byte $FF
	.byte $FF
	.byte $FF
	.byte $FF
	.byte $FF
	.byte $FF
	.byte $00	;
	.byte $7E
	.byte $3F
	.byte $5F
	.byte $5E
	.byte $3E
	.byte $7F
	.byte $76
	.byte $5F
	.byte $DF
	.byte $6E
	.byte $2E
	.byte $5E
	.byte $DE
	.byte $EE
	.byte $6E
	.byte $6E
	.byte $3E
	.byte $27
	.byte $CF
	.byte $7F
	.byte $4D
	.byte $3F
	.byte $3E

.if 0
book_edge_colors:
	.byte $00,$00,$00,$F0,$F0,$00,$00,$00
	.byte $00,$00,$F4,$30,$30,$F0,$32,$F0
	.byte $30,$F4,$F0,$F4,$F0,$30,$30,$28
	.byte $F4,$32,$12,$F0,$F4,$F4,$F4,$F4
	.byte $30,$F4,$F0,$30,$30,$30,$00,$00
	.byte $00,$00,$00,$00,$00,$00,$00,$00
.endif
