; Main part of videlectrix logo

; Using background color $00

playfield0_left:
	.byte $80,$80,$80,$80;,$00,$00,$00,$00

playfield0_right:
	.byte $00,$00,$00,$00,$B0,$A0,$90;,$B0

playfield1_left:
	.byte $B0,$B0,$B4,$E0,$E5,$E5,$45,$45

playfield2_left:
	.byte $00,$42,$42,$42,$5B,$52,$4A,$5B

playfield1_right:
	.byte $00,$10,$10,$10,$BA,$13,$12,$92

playfield2_right:
	.byte $00,$00,$02,$00,$2A,$12,$12,$2A
