; Using background color $00
;left_colors:
;	.byte $44,$44,$84
;	.byte $84,$84,$84,$84,$84,$84,$84,$84
;	.byte $00

;right_colors:
;	.byte $C6,$C6,$0E
;	.byte $0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E
;	.byte $00

playfield0_left:
	.byte $C0,$C0,$C0
	.byte $80,$80,$80,$80,$00,$00,$00,$00

playfield1_left:
	.byte $B8,$B8,$B8
	.byte $B0,$B0,$B4,$E0,$E5,$E5,$45,$45

playfield2_left:
	.byte $00,$00,$00
	.byte $00,$42,$42,$42,$5B,$52,$4A,$5B

playfield0_right:
	.byte $00,$00,$00
	.byte $00,$00,$00,$00,$B0,$A0,$90,$B0

playfield1_right:
	.byte $00,$00,$00
	.byte $00,$10,$10,$10,$BA,$13,$12,$92

playfield2_right:
	.byte $00,$00,$00
	.byte $00,$00,$02,$00,$2A,$12,$12,$2A
